---
title: "model"
author: "Michael Goldschlager"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

### Packages

```{r, echo = FALSE}
library(tidyverse) #dplyr functions mainly
library(DBI) #database
library(RSQLite) #database
library(tictoc) #timing code execution

library(xgboost) # Load XGBoost
library(caret) # Load Caret
library(OptimalCutpoints) # Load optimal cutpoints
library(ggplot2) # Load ggplot2
library(xgboostExplainer) # Load XGboost Explainer
library(pROC) # Load proc
library(SHAPforxgboost) # Load shap for XGBoost
```

### Set Working Directory

```{r}
#wd <- dirname(sys.frame(1)$ofile) #gets the directory where this script is located
#setwd(wd) #sets the working directory to the directory of this script, this is so relative paths can be used below
```

### Connect to Database

```{r}
connection <- DBI::dbConnect(RSQLite::SQLite(), "./data/pbp_db") #create connection for db
```

### Get nfl_data_set table from the database
```{r}
nfl_data_set <- dplyr::tbl(connection, "nfl_data_set") #get the nfl_data_set table from the db
```

# Data Preparation

### Select rows and columns from nfl_data_set we want for the model

```{r}
model_basic_data_use <- nfl_data_set %>% 
  dplyr::filter(season %in% c(2021, 2020, 2019, 2018) & season_type == "REG") %>% 
  dplyr::select(point_differential, season, week, 
                home_score_5w_avg, off_pass_yards_tot_home_5w_avg, off_rush_yards_tot_home_5w_avg, 
                away_score_5w_avg, off_pass_yards_tot_away_5w_avg, off_rush_yards_tot_away_5w_avg, 
                home_point_differential_5w_avg, away_point_differential_5w_avg) %>% 
  dplyr::collect()
```

### Split data into training and testing

```{r}
train_basic <- model_basic_data_use[model_basic_data_use$season %in% c(2018, 2019, 2020), ]
test_basic <- setdiff(model_basic_data_use, train_basic)
```

### Convert data to DMatrix

```{r}
dtrain_basic <- xgb.DMatrix(data = as.matrix(train_basic[, -1]), label = train_basic$point_differential)
dtest_basic <- xgb.DMatrix(data = as.matrix(test_basic[, -1]), label = test_basic$point_differential)
```

# XGBoost Model

### Train Model

```{r}
set.seed(111111)
model_basic <- xgboost(data = dtrain_basic, #set training data
                      nrounds = 100, #set number of rounds
                      verbose = 1, #prints out fit
                      print_every_n = 20 #prints out result every 20th iteration
                      )
```

### Variable Importance

```{r}
# Extract importance
imp_mat <- xgb.importance(model = model_basic)
# Plot importance (top 10 variables)
xgb.plot.importance(imp_mat, top_n = 10)
```
### Test Model

```{r}
library(Metrics)

basic_model_preds <- predict(model_basic, dtest_basic)

rmse(test_basic$point_differential, basic_model_preds)
```

